################################################################################
# Least-privilege IAM for app-tier EC2 instance profile.
# SEC-01 remediation — replaces the AWS-managed PowerUserAccess policy with a
# custom policy whose actions and resources are scoped to exactly what the
# the application has been observed using during the 30-day CloudTrail
# IAM Access Analyser observation window.
#
# The list of permitted actions is generated by scripts/iam-policy-generator.py
# from CloudTrail logs — this Terraform file is the human-reviewed,
# version-controlled artifact derived from that output.
################################################################################

data "aws_iam_policy_document" "assume" {
  statement {
    actions = ["sts:AssumeRole"]
    principals {
      type        = "Service"
      identifiers = ["ec2.amazonaws.com"]
    }
  }
}

resource "aws_iam_role" "app_tier" {
  name               = "app-tier-${var.environment}"
  assume_role_policy = data.aws_iam_policy_document.assume.json
  description        = "the application app-tier least-privilege role (SEC-01)"
  tags               = merge(var.tags, { Finding = "SEC-01" })
}

############################
# Custom inline policy — least privilege
############################

data "aws_iam_policy_document" "app_tier" {
  # S3 — document vault read + write on the documents/ prefix only.
  statement {
    sid    = "S3DocumentVault"
    effect = "Allow"
    actions = [
      "s3:GetObject", "s3:PutObject", "s3:DeleteObject",
      "s3:GetObjectVersion", "s3:GetObjectTagging", "s3:PutObjectTagging",
    ]
    resources = ["${var.document_vault_bucket_arn}/documents/*"]
  }
  statement {
    sid       = "S3DocumentVaultList"
    effect    = "Allow"
    actions   = ["s3:ListBucket", "s3:GetBucketLocation"]
    resources = [var.document_vault_bucket_arn]
    condition {
      test     = "StringLike"
      variable = "s3:prefix"
      values   = ["documents/*", "documents/"]
    }
  }

  # RDS — IAM-authenticated database connection (rds-db:connect)
  statement {
    sid       = "RDSConnect"
    effect    = "Allow"
    actions   = ["rds-db:connect"]
    resources = ["arn:aws:rds-db:${var.region}:${var.account_id}:dbuser:${var.rds_resource_id}/app_db_user"]
  }

  # SSM Parameter Store — read /app/* parameters
  statement {
    sid       = "SSMParameterStore"
    effect    = "Allow"
    actions   = ["ssm:GetParameter", "ssm:GetParameters", "ssm:GetParametersByPath"]
    resources = ["arn:aws:ssm:${var.region}:${var.account_id}:parameter/app/*"]
  }

  # Secrets Manager — read app-prefixed secrets only
  statement {
    sid       = "SecretsManagerApp"
    effect    = "Allow"
    actions   = ["secretsmanager:GetSecretValue", "secretsmanager:DescribeSecret"]
    resources = ["arn:aws:secretsmanager:${var.region}:${var.account_id}:secret:app/*"]
  }

  # KMS — decrypt with the keys used by the resources above
  statement {
    sid       = "KMSDecrypt"
    effect    = "Allow"
    actions   = ["kms:Decrypt", "kms:GenerateDataKey", "kms:DescribeKey"]
    resources = var.kms_key_arns
    condition {
      test     = "StringEquals"
      variable = "kms:ViaService"
      values = [
        "s3.${var.region}.amazonaws.com",
        "secretsmanager.${var.region}.amazonaws.com",
        "ssm.${var.region}.amazonaws.com",
      ]
    }
  }

  # CloudWatch Logs — write to app-tier log group only
  statement {
    sid    = "CloudWatchLogs"
    effect = "Allow"
    actions = [
      "logs:CreateLogStream", "logs:PutLogEvents",
      "logs:DescribeLogStreams", "logs:CreateLogGroup",
    ]
    resources = ["arn:aws:logs:${var.region}:${var.account_id}:log-group:/app/*"]
  }

  # CloudWatch metrics — publish the application custom metrics
  statement {
    sid       = "CloudWatchMetrics"
    effect    = "Allow"
    actions   = ["cloudwatch:PutMetricData"]
    resources = ["*"]
    condition {
      test     = "StringEquals"
      variable = "cloudwatch:namespace"
      values   = ["PLM/App"]
    }
  }
}

resource "aws_iam_role_policy" "app_tier" {
  name   = "app-tier-policy"
  role   = aws_iam_role.app_tier.id
  policy = data.aws_iam_policy_document.app_tier.json
}

############################
# SSM managed instance core — required for SEC-05 (Patch Manager)
############################

resource "aws_iam_role_policy_attachment" "ssm" {
  role       = aws_iam_role.app_tier.name
  policy_arn = "arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore"
}

resource "aws_iam_instance_profile" "app_tier" {
  name = "app-tier-${var.environment}"
  role = aws_iam_role.app_tier.name
  tags = var.tags
}

############################
# IAM Access Analyser (organisation-level) — so SEC-01 type drift is caught
# in future audits.
############################

resource "aws_accessanalyzer_analyzer" "this" {
  count         = var.create_access_analyser ? 1 : 0
  analyzer_name = "plm-${var.environment}"
  type          = "ACCOUNT"
  tags          = merge(var.tags, { Finding = "SEC-01 SEC-03" })
}
